package com.example.pallettracker;

import android.annotation.SuppressLint;
import android.content.DialogInterface;
import android.content.Intent;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.view.LayoutInflater;
import android.database.Cursor;

import androidx.appcompat.app.AlertDialog;
import androidx.appcompat.app.AppCompatActivity;

import java.util.List;


public class MainActivity extends AppCompatActivity {

    private MyDatabaseHelper dbHelper;
    private LinearLayout verticalLayout;





    private int total_Pallets = 0;

    @Override
    protected void onCreate(Bundle savedInstanceState) {

        //Nav Buttons too different pages
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        dbHelper = new MyDatabaseHelper(this);
        verticalLayout = findViewById(R.id.Pallet_Info_ButtonsList);

        Button calculator = (Button) findViewById(R.id.b_To_Calc);
        calculator.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Intent intent_calc = new Intent(MainActivity.this, Calculator.class);
                startActivity(intent_calc);
            }
        });
        Button notes = (Button) findViewById(R.id.b_To_Notes);
        notes.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Intent intent_notes = new Intent(MainActivity.this, Notes.class);
                startActivity(intent_notes);
            }
        });
        Button archive = (Button) findViewById(R.id.b_To_Archive);
        archive.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
//                Intent intent = new Intent(MainActivity.this, Prompt_Pallet_Info.class);
//                startActivity(intent);
            }
        });
        //------------------------------------------------------------------------------------


        Button AddPallet = findViewById(R.id.New_Pallet);
        AddPallet.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {

                total_Pallets += 1;
                createNumberedButtons(total_Pallets);
                showInputDialog();
            }
        });

    }



    protected void showInputDialog() {
        LayoutInflater layoutInflater = LayoutInflater.from(this);
        View promptView = layoutInflater.inflate(R.layout.custom_layout, null);

        AlertDialog.Builder alertDialogBuilder = new AlertDialog.Builder(this);
        alertDialogBuilder.setView(promptView);
        alertDialogBuilder.setTitle("Pallet Information");

        final EditText companyEditText = promptView.findViewById(R.id.Company);
        final EditText supplierEditText = promptView.findViewById(R.id.Supplier);
        final EditText unitsEditText = promptView.findViewById(R.id.TotalNumber_Units);
        final EditText costEditText = promptView.findViewById(R.id.TotalNumber_Price);

        alertDialogBuilder.setCancelable(false)
                .setPositiveButton("OK", new DialogInterface.OnClickListener() {
                    public void onClick(DialogInterface dialog, int id) {
                        String company = companyEditText.getText().toString();
                        String supplier = supplierEditText.getText().toString();
                        int units = Integer.parseInt(unitsEditText.getText().toString());
                        float cost = Float.parseFloat(costEditText.getText().toString());

                        // Insert data into your database using your insert statement
                        dbHelper.insertData( company, supplier, units, cost);

                        // Incremental ID can be automatically generated by the database
                        // (e.g., auto-increment primary key)
                        // ...
                    }
                });

        AlertDialog alert = alertDialogBuilder.create();
        alert.show();
    }
    private void createNumberedButtons(int count) {
        for (int i = 1; i <= count; i++) {
            Button button = new Button(this);
            button.setText(String.valueOf(i));
            button.setId(i); // Set a unique ID for each button (optional)

            // Set an onClickListener for each button
            button.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    int buttonNumber = v.getId();
                    showDataForButton(buttonNumber);
                }
            });

            // Add the button to the vertical layout
            verticalLayout.addView(button);
        }
    }
    private void showDataForButton(int buttonNumber) {
        SQLiteDatabase db = dbHelper.getReadableDatabase();

        // Query your database based on the button number
        Cursor cursor = db.rawQuery("SELECT * FROM my_table WHERE _id = ?", new String[]{String.valueOf(buttonNumber)});

        if (cursor.moveToFirst()) {
            @SuppressLint("Range") String company = cursor.getString(cursor.getColumnIndex("company"));
            @SuppressLint("Range") String supplier = cursor.getString(cursor.getColumnIndex("supplier"));
            @SuppressLint("Range") int units = cursor.getInt(cursor.getColumnIndex("units"));
            @SuppressLint("Range") float cost = cursor.getFloat(cursor.getColumnIndex("cost"));

            // Create an alert dialog to display the data
            AlertDialog.Builder alertDialogBuilder = new AlertDialog.Builder(this);
            alertDialogBuilder.setTitle("Data for Button " + buttonNumber);
            alertDialogBuilder.setMessage("Company: " + company + "\n" +
                    "Supplier: " + supplier + "\n" +
                    "Units: " + units + "\n" +
                    "Cost: $" + cost);
            alertDialogBuilder.setPositiveButton("OK", null);
            alertDialogBuilder.show();
        } else {

        }

        cursor.close();
        db.close();
    }



}

